# Generated by Django 4.0.4 on 2022-05-29 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabanaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='HabanaFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=240)),
                ('field_type', models.IntegerField(choices=[(1, 'Texto'), (2, 'Texto Largo'), (3, 'Selección única'), (4, 'Selección multiple')])),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habanaforms.habanaform')),
            ],
        ),
        migrations.CreateModel(
            name='HabanaFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habana_form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habanaforms.habanaformfield')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='habanaformresponse',
            constraint=models.UniqueConstraint(fields=('owner', 'habana_form_response'), name=' unique_response'),
        ),
    ]
