# Generated by Django 4.0.4 on 2022-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habanaforms', '0002_alter_habanaform_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='habanaform',
            name='available_from',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='habanaform',
            name='available_until',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='habanaform',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habanaformfield',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
