# Generated by Django 4.0.4 on 2022-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habanaforms', '0006_alter_habanaformresponse_value'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='habanaformresponse',
            name=' unique_response',
        ),
        migrations.AddConstraint(
            model_name='habanaformresponse',
            constraint=models.UniqueConstraint(fields=('owner', 'habana_form_field'), name=' unique_response'),
        ),
    ]
