# Generated by Django 4.0.4 on 2022-05-29 02:25

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('habanaforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habanaform',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
