# Generated by Django 4.0.4 on 2022-05-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habanaforms', '0003_habanaform_available_from_habanaform_available_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habanaformresponse',
            old_name='habana_form_response',
            new_name='habana_form_field',
        ),
        migrations.AddField(
            model_name='habanaformresponse',
            name='value',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
