/* eslint-disable @typescript-eslint/no-var-requires */

// eslint-disable-next-line no-undef
const tailwindConfig = require('../tailwind.config');
// eslint-disable-next-line no-undef
const fs = require('fs');

function getTailwindScreens() {
    let sass = `// This file is automatically generated, do not edit \n`;

    let screensMap = '$screens: (\n';

    for (let key in tailwindConfig.theme.screens) {
        const screens = tailwindConfig.theme.screens;

        if (key in screens) {
            let value = tailwindConfig.theme.screens[key];

            screensMap += `    "${key}": ${value}, \n`;
        }
    }

    screensMap += ');';
    sass += screensMap;

    return sass;
}

async function writeTailwindToSass() {
    let screenData = getTailwindScreens();
    fs.writeFile('assets/scss/_tailwind-screens.scss', screenData, function (err, _file) {
        if (err) throw err;
    });
}

writeTailwindToSass();
