# Generated by Django 4.0.4 on 2022-05-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_hard_score_usermodel_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_admin',
        ),
    ]
